### PR TITLE
Run the mongodb-grafana project using docker-compose

### PR DESCRIPTION
**Pull request by gkatzioura**
This is a great project, which I was really in need of. Thank you 👍 
I added two dockerfiles to boostrap the experience.
One is for the proxy, thus a docker image is created for the proxy.
The other one is for the Grafana, thus we end up with a docker Grafana images which has preinstalled the 

Apparently the above can be used together using docker compose, thus with one line the user can have a mongodb instance, a mongodb proxy and the Grafana server with the mongodb plugin preinstalled.

```
docker-compose -f stack.yaml build
MONGO_USER=root MONGO_PASSWORD=root DB_PATH=~/grafana-mongo  docker-compose -f stack.yaml up
```

Kind Regards

### CODE REVIEW

**Comment by gkatzioura** [comment]
I made also a blog that explains each step and fle created 
https://egkatzioura.com/2019/02/26/docker-basics-docker-compose/

**Comment by timstallinger** [comment]
I get HTTP Error Bad Gateway, when I run your docker as described. 
Mongo-proxy_1 output:
`
[...]
Server is listening on port 3333
`
grafana_1 docker output:
`
dial tcp 127.0.0.1:3333: connect: connection refused.
`
My datasource config:
URL: http://localhost:3333
Access: Server
Auth: None
MongoDB details: 
- URL: mongodb://root:root@localhost:27017
- MongoDB Database: test

edit: Server listening on port 333 -> Server listening on port 3333

**Comment by gkatzioura** [comment]
`http://localhost:3333` instead of localhost you should use the actual proxy name on the compose file

**Comment by timstallinger** [comment]
You're talking about the HTTP URL, right? I don't see, where I put `localhost` instead of `http://localhost:3333`. My compose file only uses the networks. Therefore mongo-proxy is connected to the backend, like in your blogpost. So what is the "proxy name"? I would open an issue on your fork, but you don't allow issues there.

**Comment by timstallinger** [comment]
Solved this by putting URL `http://mongo-proxy:3333` and MongoDB URL `mongodb://root:root@mongo:27017`.

**Comment by shellmann** [comment]
@gkatzioura I always get `{ message: "Invalid API key" }` when I try to access http://localhost:3000/. Do you have any idea?

**Comment by chinky1** [comment]
Hi Team, MongoDb I am using is external I don't want to install mongoDb in container. Please suggest how to connect mongoDb outside the container.  what Url and and Db path I have to provide

**Comment by gkatzioura** [comment]
There is no interest on this one, so closing ticket.

**Pull request closed without merging**
